from selenium import webdriver
import time
driver = webdriver.Chrome()  # 调用chrome浏览器
driver.get('https://sit-ccp.uce.cn/index.html#/login')
time.sleep(3)
driver.maximize_window()
账号=driver.find_element_by_css_selector('#login-form > form > div:nth-child(2) > div > div.el-input > input').send_keys('80239409')
密码=driver.find_element_by_xpath('//*[@id="login-form"]/form/div[3]/div/input[2]').send_keys('zhang_1231212')
点击登录=driver.find_element_by_xpath('//*[@id="login-form"]/form/div[4]/div/button/span').click()
time.sleep(1)
选择订单管理=driver.find_element_by_xpath('/html/body/div/div[2]/div[1]/div[2]/ul/li[2]/a/span').click()
time.sleep(1)#等待2秒
进入订单管理=driver.find_element_by_xpath('/html/body/div/div[2]/div[1]/div[2]/ul/li[2]/ul/li[2]/a/span').click()
time.sleep(2)#等待2秒
输入运单号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[2]/textarea').send_keys('889900008511503,889900008511497,889900008511481,889900008511480')
time.sleep(1)

查询按钮=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[6]/button').click()
time.sleep(1)
选择订单编号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[1]/div[1]/i').click()
time.sleep(1)
子单=driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[4]').click()
time.sleep(1)
清空输入子单号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[2]/textarea').clear()
time.sleep(1)
输入子单编号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[2]/textarea').send_keys('319000350159')
time.sleep(1)
查询按钮=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[6]/button').click()
time.sleep(1)
选择订单编号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[1]/div[1]/i').click()
time.sleep(1)
外部订单号=driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[3]').click()
time.sleep(1)
清空输入运单号1=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[2]/textarea').clear()
time.sleep(1)
输入外部订单号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[2]/textarea').send_keys('WAI1231212')
time.sleep(1)
查询按钮=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[6]/button').click()
time.sleep(1)
选择订单编号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[1]/div[1]/i').click()
time.sleep(1)
订单编号=driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/ul/li[2]').click()
time.sleep(1)
清空输入运单号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[2]/textarea').clear()
time.sleep(1)
输入订单编号2=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[2]/textarea').send_keys('CCP171210165407040053,CCP171214201527000040,CCP171214205118000045,CCP171214193856000020')
time.sleep(1)
查询按钮=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[6]/button').click()
time.sleep(1)
清空输入运单号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/div[2]/textarea').clear()
time.sleep(2)
xinzeng=driver.find_element_by_xpath('//*[@id="topBar"]/div/button[1]/span').click()
time.sleep(1)
# yundanbianhao=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[1]/div/div/input').send_keys('A123121212')
waibudanhao=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[2]/div/div/input').send_keys('WAI1231212')
jijianren=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[3]/div/div/input').clear()
jijianren=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[3]/div/div/input').send_keys('笑1笑')
jijiangongsi=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[4]/div/div/input').clear()
jijiangongsi=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[4]/div/div/input').send_keys('无敌幸运星')
jijianshouji=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[5]/div/div/input').clear()
jijianshouji=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[5]/div/div/input').send_keys('13888888888')
# jijiandizhi=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[7]/div/div[1]/div[1]/input').click()
# # 省份=driver.find_element_by_tag_name('上海').click()
# 省份=driver.find_element_by_xpath('/html/body/div[3]/div/div[1]/ul/li[5]').click()
xiangxindizhi=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[8]/div/div[1]/input').clear()
xiangxindizhi=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[8]/div/div[1]/input').send_keys('江苏省苏州市姑苏区人民路858号')
shoujianren=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[9]/div/div/input').clear()
shoujianren=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[9]/div/div/input').send_keys('小白')
shoujiangongsi=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[10]/div/div/input').send_keys('优速快递')
shoujiandianhua=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[11]/div/div/input').send_keys('13666666666')
shoujianxiangxindizhi=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[14]/div/div/input').send_keys('上海市浦东新区世博大道2820号')
jianshu=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[15]/div/div/input').clear()
jianshu1=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[15]/div/div/input').send_keys('1')
zhongliang=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[16]/div/div/input').clear()
zhongliang=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[16]/div/div/input').send_keys('2')
daishoukuai=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[17]/div/div/input').send_keys('10')
daofukuan=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[18]/div/div/input').send_keys('66')
qianhuidan=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[20]/div/label/span/span').click()
wupinjiazhi=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[21]/div/div/input').send_keys('888')
beizhu=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[22]/div/div/textarea').send_keys('测试数据随便删！！')
xinzenganniiu=driver.find_element_by_xpath('/html/body/div[1]/div[2]/div[2]/div[2]/div/div/div[4]/div[1]/div/div[3]/div/button[2]/span').click()
time.sleep(1)
清空输入运单号=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[1]/i').click()
time.sleep(2)
查询按钮=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[6]/button').click()
time.sleep(1)
修改=driver.find_element_by_css_selector('body > div.app.default > div.uce-layout.flexbox > div.flexbox.right-slide > div.uce-view > div > div.el-table.el-table--fit.el-table--striped.el-table--border.el-table--enable-row-transition > div.el-table__fixed-right > div.el-table__fixed-body-wrapper > table > tbody > tr > td.el-table_1_column_14.is-center > div > a:nth-child(2) > button > span > i').click()
time.sleep(1)
jianshu=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[15]/div/div/input').clear()
jianshu1=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[15]/div/div/input').send_keys('2')
time.sleep(1)
zhongliang=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[16]/div/div/input').clear()
zhongliang=driver.find_element_by_xpath('//*[@id="addDialog"]/form/div[16]/div/div/input').send_keys('2')
time.sleep(1)
保存=driver.find_element_by_xpath('/html/body/div[1]/div[2]/div[2]/div[2]/div/div[4]/div[1]/div/div[3]/div/button[2]').click()
time.sleep(1)
查询按钮=driver.find_element_by_xpath('//*[@id="topBar"]/form/div[6]/button').click()
time.sleep(1)
删除=driver.find_element_by_xpath('/html/body/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[14]/div/a[3]/button/span/i').click()
time.sleep(1)
删除确定=driver.find_element_by_css_selector('body > div.el-message-box__wrapper > div > div.el-message-box__btns > button.el-button.el-button--default.el-button--primary > span').click()
截图=driver.get_screenshot_as_file("D:\\111.png")
time.sleep(5)
driver.quit()